name: Deploy Website and Run Twitch Bot

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install website dependencies
        working-directory: ./website
        run: npm ci

      - name: Build website
        working-directory: ./website
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./website/out

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install Python dependencies
        working-directory: ./bot
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Twitch bot
        working-directory: ./bot
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          BROADCASTER: ${{ secrets.BROADCASTER }}
        run: |
          python main.py &
          sleep 300  # Run the bot for 5 minutes to generate initial data

      - name: Stop Twitch bot
        run: pkill -f "python main.py"