name: Run Twitch Bot

on:
  workflow_dispatch:  # Allow manual triggers
  schedule:
    - cron: '0 */1 * * *'  # Run every hour

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r bot/requirements.txt

    - name: Run bot
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        CLIENT_ID: ${{ secrets.CLIENT_ID }}
        BROADCASTER: ${{ secrets.BROADCASTER }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --global user.email "github-actions@github.com"
        git config --global user.name "GitHub Actions"
        
        # Create and switch to leaderboard-data branch
        git checkout -b leaderboard-data || git checkout leaderboard-data
        git pull origin leaderboard-data || true
        
        python bot/main.py &
        while true; do
          sleep 300  # Wait for 5 minutes
          git add website/public/leaderboard_data.json
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update leaderboard data" && git push origin leaderboard-data)
        done